services:
  bill-db:
    image: postgres:alpine
    ports:
      - ${POSTGRES_PORT}:5432
    hostname: bill-db
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $POSTGRES_DB -U $POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    extra_hosts:
      - "host.docker.internal:host-gateway"
  bill-api:
    build:
      context: ./bill-api/
    ports:
      - 8080:8080
      - 1323:1323
    hostname: api
    env_file: .env
    volumes:
      - ./bill-api/:/usr/app
    depends_on:
      bill-db:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"
volumes:
  pgdata:
    driver: local
